---
title: "Preprocessing"
output: html_notebook
---
```{r}
d.patient = read.table('/Users/linglinhuang/Desktop/6.867/project/brca_tcga_pub2015/brca_tcga_pub2015/data_bcr_clinical_data_patient.txt', header = T, sep = '\t')
d.sample = read.table('/Users/linglinhuang/Desktop/6.867/project/brca_tcga_pub2015/brca_tcga_pub2015/data_bcr_clinical_data_sample2.txt', header = T, sep = '\t')

d = merge(d.sample, d.patient, by.x=1, by.y=1)
d = d[d$GENDER=='FEMALE' & d$RACE=='WHITE' & d$ER_STATUS_BY_IHC!= "[Not Available]" & d$IHC_HER2!='[Not Available]' ,]

sum(d$ER_STATUS_BY_IHC=='Positive')
sum(d$ER_STATUS_BY_IHC=='Negative')

sum(d$IHC_HER2=='Negative')
sum(d$IHC_HER2=='Equivocal')
sum(d$IHC_HER2=='Positive')
sum(d$IHC_HER2=='[Not Available]')


d$y = d$ER_STATUS_BY_IHC=='Positive' & d$IHC_HER2=='Negative' + 0
#sum((d$IHC_HER2=='Positive' | d$IHC_HER2=='Equivocal' | d$IHC_HER2=='Indeterminate'))

levels(d$ER_STATUS_BY_IHC)
levels(d$IHC_HER2)
```


```{r}
expr.all = read.delim('/Users/linglinhuang/Desktop/6.867/project/brca_tcga_pub2015/brca_tcga_pub2015/data_RNA_Seq_v2_expression_median.txt', header = T, sep = '\t')
colnames(expr.all) = gsub("\\.","-",colnames(expr.all))
head(expr.all)
head(d)

```

```{r}
texpr.all = t(expr.all[, -c(1,2)])
texpr.all[1:5,1:5]
colnames(texpr.all) = expr.all$Hugo_Symbol
texpr.all[1:5,1:5]
texpr.all = as.data.frame(texpr.all)
expr = merge(texpr.all, d, by.x=0, by.y=2, all=F)
expr[1:5,1:5]
sum(expr$GENDER == 'FEMALE')
sum(expr$ER_STATUS_BY_IHC == 'Positive')
sum(expr$ER_STATUS_BY_IHC == 'Negative')
sum(expr$RACE == 'WHITE')
sum(expr$y)
sum(!expr$y)

write.table(expr, '~/Dropbox/6.867project/data/sub_exp.txt', sep = '\t', row.names = T, col.names = T)

expr[1:5,20440:20453]
```

```{r}
expr = read.table('~/Dropbox/6.867project/data/sub_exp.txt', sep = '\t')

tmp = expr[,c(1:20441,20453)]
tmp[1:5, 20435:20442]

#split data into train (2/3) and test (1/3)
set.seed(1)
n = nrow(tmp)
test_idx = sample(1:n, n/3, replace = F)
test = data.matrix(tmp[test_idx,])
train = data.matrix(tmp[-test_idx,])

train[,c(20435:20442)]

write.table(test, '~/Dropbox/6.867project/data/test.txt', sep = '\t', row.names = T, col.names = T)
write.table(train, '~/Dropbox/6.867project/data/train.txt', sep = '\t', row.names = T, col.names = T)
```

